apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-collector
  annotations:
    GitLabProject: https://github.com/ma-ha/k8s-mon-collector
spec:
  selector:
    matchLabels:
      app: mon-collector
  replicas: 1
  template:
    metadata:
      labels:
        app: mon-collector
    spec:
      # automountServiceAccountToken: false
      serviceAccountName: mon-collector  
      containers:
      - name: mon-collector
        image: leancloudservices/k8s-mon-collector:1.5.1
        env:
        - name: EKOSYS_ID
          valueFrom:
            secretKeyRef:
              name: monitoring-secret
              key: id
        - name: EKOSYS_KEY
          valueFrom:
            secretKeyRef:
              name: monitoring-secret
              key: key
        - name: CTX_SERVER
          value: https://10.0.0.1:443
        - name: DATA_INTERVAL
          value: "30000"
        - name: NODE_ENV
          value: PRD
        - name: AZMON_COLLECT_ENV
          value: "False"
        resources:
          requests:
            memory: "56Mi"
            cpu: "5m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        securityContext:
          seccompProfile: 
            type: RuntimeDefault
          capabilities: 
            drop:
            - ALL
          procMount: Default
          runAsUser: 1001
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
