apiVersion: v1
kind: ServiceAccount
metadata:
  name: mon-collector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mon-collector
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mon-collector
subjects:
- kind: ServiceAccount
  name: mon-collector
roleRef:
  kind: Role
  name: mon-collector
  apiGroup: rbac.authorization.k8s.io