MONITORING_CENTRAL_URL: https://k8s-mon.online-service.cloud
DATA_INTERVAL: 30000
LOG_INTERVAL: 10000
LOG_RENEW_STREAM_MIN: 30
LOG_SND_MAX_CNT: 30
ACCESS_LOG_REGEXP: '^(\S+) (\S+) (\S+) \[([\w:/]+\s[+\-]\d{4})\] "(\S+) (\S+)\s*(\S+)?\s*" (\d{3}) (\S+) (\S+) "([^"]+)"'
ACCESS_LOG_REGEXP_IP: 1
ACCESS_LOG_REGEXP_METHOD: 5
ACCESS_LOG_REGEXP_URL: 6
ACCESS_LOG_REGEXP_CLT: 11
ACCESS_IP_ERR_ANOMALY: 20  # per DATA_INTERVAL